import {useCharacterStore} from "../stores/characterStore.ts";

const warnMessage = `# ${'='.repeat(85)}
# This file is generated automatically with Pamyu. Do not edit this file manually.
# ${'='.repeat(85)}\n\n`;

export function get_characters_script(): string {
    const charactersStrings: string[] = []

    useCharacterStore().getCharacters.forEach((character) => {
        let options = ""
        if (character.color) options += `, color="${character.color}"`
        if (character.what_prefix) options += `, what_prefix="${character.what_prefix}"`
        if (character.what_suffix) options += `, what_suffix="${character.what_suffix}"`
        if (character.who_prefix) options += `, who_prefix="${character.who_prefix}"`
        if (character.who_suffix) options += `, who_suffix="${character.who_suffix}"`
        const characterString = `define ${character._id} = Character("${character.name}"${options})`
        charactersStrings.push(characterString)
    })
    return warnMessage + charactersStrings.join("\n")
}